### ISSUE TITLE
1.13でtellraw構文エラー

### ISSUE THREAD

**Issue by ken-kentan** [ucchyocean/UndineMailer#101]
埋め込みコマンドの構文が不正です。

```
XXX issued server command: /umail message 6
Expected whitespace to end one argument, but found trailing data
...a":[{"text":"# "},{"text":"[宛先を追加する]","color":"aqua","clickEvent":{"action":"suggest_command","value":"/umail to 2 "},"hoverEvent":{"action":"show_text","value":{"text":"宛先を追加するには、
ここをクリックして表示されるコマンドに続けて、
宛先のプレイヤー名を入力してください。"}}}]}<--[HERE]
```

**Comment by RoboMWM** [comment]
I wonder if ucchyocean would consider using the spigot API so he can use BaseComponents instead of `/tellraw` commands.

**Comment by ucchyocean** [comment]
原因がわかりました。
1.13 以降のバージョンでは、tellrawコマンドのパラメータ中に改行を含めると、コマンドエラーになるようです。
回避策としては、メッセージ設定ファイルで、該当メッセージの改行コードを除去してください。

- 編集するファイル：　`plugins\UndineMailer\lang\messages_ja.yml`
- 編集内容：　ファイル内の「\n」を探して、すべて除去してください。例↓

<pre>
EditmodeToAddToolTip: '宛先を追加するには、\nここをクリックして表示されるコマンドに続けて、\n宛先のプレイヤー名を入力してください。'
</pre>
↓
<pre>
EditmodeToAddToolTip: '宛先を追加するには、ここをクリックして表示されるコマンドに続けて、宛先のプレイヤー名を入力してください。'
</pre>

その後、サーバー再起動などで設定を再読み込みすると、解決できるはずです。

-----

I found the cause of this issue.
In Bukkit version 1.13 or later, it seems that a command error will occur if a newline is included in the tellraw command parameters.
As a workaround, remove `\n` code of the message in the message configuration file (`message_en.yml`).

For example,
<pre>
EditmodeToAddToolTip: 'To add new recipient,\nclick here and\ninput recipient player name to chat window.'
</pre>
↓
<pre>
EditmodeToAddToolTip: 'To add new recipient, click here and input recipient player name to chat window.'
</pre>

**Comment by ken-kentan** [comment]
解決しました！
ありがとうございます。
