### ISSUE TITLE
Adding adjustable delay of log-in notification.

### ISSUE THREAD

**Issue by ucchyocean** [ucchyocean/UndineMailer#37]
Can you add mail notification delay when player log in? I use this with Authme_Reloaded and players have to log in first in order to play. If you can, please set default delay time to 30 seconds.

**Comment by ucchyocean** [comment]
I feel, "default = 30 seconds" is too long. Almost of users do not use "Authme_Reloaded".\\
Around 3 seconds is suitable.

**Comment by madtomic** [comment]
How about configurable?

**Comment by ucchyocean** [comment]
Yes, I think that should be adjustable by using config.yml.

Like this:
<pre>
# Mail notification delay seconds on player logs-in.
loginNotificationDelaySeconds: 3
</pre>

**Comment by ucchyocean** [comment]
Fixed
