### ISSUE TITLE
1.4.14

### ISSUE THREAD

**Issue by madtomic** [ucchyocean/UndineMailer#64]
Will you be updating the English version?

http://forum.minecraftuser.jp/viewtopic.php?f=38&t=24681

**Comment by ucchyocean** [comment]
Sorry, I could not upload the file into BukkitDev. I don't know why...

If you want to use 1.4.14, please download from Japanese forum page.
http://forum.minecraftuser.jp/viewtopic.php?f=38&t=24681
It will work as English version in English Windows.
