### ISSUE TITLE
Menu item "Add recipient group" shown when lacking permissions

### ISSUE THREAD

**Issue by sgrayme** [ucchyocean/UndineMailer#84]
While all permissions for group management are denied, the "/mail write" menu shows the option for "Add recipient group". Clicking the text results in a permissions message, but ideally, the menu line should not be displayed at all in that situation. The workaround is changing the translation line to be empty, but that leaves an awkward gap in the menu.

This is a very mild/non-critical matter, but I'm noting it because there is no benefit to showing an unusable menu item.

**Comment by ucchyocean** [comment]
sgrayme,
Thanks for your reporting.
OK, I will think about that.

**Comment by ucchyocean** [comment]
Fixed.
I had checked the modification point, it was OK.
![2016-08-31_01 47 53](https://cloud.githubusercontent.com/assets/2563444/18099904/a7d1dbe4-6f23-11e6-9e67-961f07e4f1c1.png)
